"""add_missing_risk_entry_and_other_models

Revision ID: 2b657a64980d
Revises: 0dcc5cacb5b1
Create Date: 2026-03-15 14:48:33.181827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b657a64980d'
down_revision: Union[str, None] = '0dcc5cacb5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_phase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'UPCOMING', name='phase_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('risk_ref', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('likelihood', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risk_likelihood'), nullable=False),
    sa.Column('impact', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risk_impact'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('control_ref', sa.String(length=100), nullable=True),
    sa.Column('risk_status', sa.Enum('OPEN', 'IN_REVIEW', 'MITIGATED', 'ACCEPTED', name='risk_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_entry_engagement_id'), 'risk_entry', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_risk_entry_tenant_id'), 'risk_entry', ['tenant_id'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('initials', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('risk_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('control_type', sa.Enum('PREVENTIVE', 'DETECTIVE', 'CORRECTIVE', name='control_type'), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('EFFECTIVE', 'DEFICIENT', 'NOT_TESTED', 'COMPENSATING', name='control_status'), nullable=False),
    sa.Column('last_tested', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_entry.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_entry')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_risk_entry_tenant_id'), table_name='risk_entry')
    op.drop_index(op.f('ix_risk_entry_engagement_id'), table_name='risk_entry')
    op.drop_table('risk_entry')
    op.drop_table('engagement_phase')
    # ### end Alembic commands ###
