"""Gap 4 Multi Jurisdiction Standards

Revision ID: 42b05e8f9d7e
Revises: ba6f54a1f0de
Create Date: 2026-03-12 07:41:32.187998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b05e8f9d7e'
down_revision: Union[str, None] = 'ba6f54a1f0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement', sa.Column('standards_framework', sa.Enum('ICAI_SA', 'PCAOB_AS', 'ISA', 'FRC_ISA', name='standards_framework'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement', 'standards_framework')
    # ### end Alembic commands ###
