"""Gap 2 Human Judgment Layer

Revision ID: 4df3b99124f2
Revises: 61f94b18d54f
Create Date: 2026-03-12 07:29:54.262615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df3b99124f2'
down_revision: Union[str, None] = '61f94b18d54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_update',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_tag', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'APPLIED', name='regulatory_update_status'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_log_action'), 'system_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_system_audit_log_created_at'), 'system_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_audit_log_tenant_id'), 'system_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_system_audit_log_user_id'), 'system_audit_log', ['user_id'], unique=False)
    op.create_table('professional_judgment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', name='judgment_status'), nullable=False),
    sa.Column('signed_by', sa.String(length=255), nullable=True),
    sa.Column('icai_reg_no', sa.String(length=20), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('sa_versions', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa_checklist_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('standard_ref', sa.String(length=50), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLIANT', 'NON_COMPLIANT', 'NOT_APPLICABLE', name='sa_checklist_status'), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('platform_user', sa.Column('icai_reg_no', sa.String(length=20), nullable=True))
    op.add_column('seal_signature', sa.Column('ca_icai_reg_no', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seal_signature', 'ca_icai_reg_no')
    op.drop_column('platform_user', 'icai_reg_no')
    op.drop_table('sa_checklist_item')
    op.drop_table('rules_snapshot')
    op.drop_table('professional_judgment')
    op.drop_index(op.f('ix_system_audit_log_user_id'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_tenant_id'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_created_at'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_action'), table_name='system_audit_log')
    op.drop_table('system_audit_log')
    op.drop_table('regulatory_update')
    # ### end Alembic commands ###
