# pyre-ignore-all-errors
"""expand_engagement_types

Revision ID: 61f94b18d54f
Revises: 7d7f4ef8f7d5
Create Date: 2026-03-08 06:12:10.665372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61f94b18d54f'
down_revision: Union[str, None] = '7d7f4ef8f7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('carbon_footprint_scope_1', sa.Float(), nullable=True),
    sa.Column('carbon_footprint_scope_2', sa.Float(), nullable=True),
    sa.Column('carbon_footprint_scope_3', sa.Float(), nullable=True),
    sa.Column('board_diversity_pct', sa.Float(), nullable=True),
    sa.Column('supply_chain_transparency_index', sa.Float(), nullable=True),
    sa.Column('active_regulatory_fines', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forensic_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_velocity_score', sa.Float(), nullable=True),
    sa.Column('benfords_law_deviation', sa.Float(), nullable=True),
    sa.Column('offshore_routing_instances', sa.Integer(), nullable=True),
    sa.Column('ubo_opacity_index', sa.Float(), nullable=True),
    sa.Column('sanctions_hit_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_override',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('original_risk_score', sa.Float(), nullable=False),
    sa.Column('original_confidence', sa.Float(), nullable=False),
    sa.Column('overridden_risk_score', sa.Float(), nullable=False),
    sa.Column('overridden_by_user', sa.String(length=120), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('reviewer_confirmation', sa.Boolean(), nullable=False),
    sa.Column('override_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_opinion', 'decision_hashes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('audit_opinion', 'exception_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.add_column('engagement', sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('engagement', sa.Column('seal_hash', sa.String(length=64), nullable=True))
    op.alter_column('erp_connection', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('erp_connection', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('erp_sync_log', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_platform_user_tenant_active'), table_name='platform_user')
    op.drop_index(op.f('ix_platform_user_tenant_email'), table_name='platform_user')
    op.alter_column('seal_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_seal_session_engagement'), table_name='seal_session')
    op.drop_index(op.f('ix_seal_signature_session'), table_name='seal_signature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_seal_signature_session'), 'seal_signature', ['seal_session_id'], unique=False)
    op.create_index(op.f('ix_seal_session_engagement'), 'seal_session', ['engagement_id'], unique=False)
    op.alter_column('seal_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_platform_user_tenant_email'), 'platform_user', ['tenant_id', 'email'], unique=False)
    op.create_index(op.f('ix_platform_user_tenant_active'), 'platform_user', ['tenant_id', 'is_active'], unique=False)
    op.alter_column('platform_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('erp_sync_log', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('erp_connection', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('erp_connection', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('engagement', 'seal_hash')
    op.drop_column('engagement', 'sealed_at')
    op.alter_column('audit_opinion', 'exception_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('audit_opinion', 'decision_hashes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_table('decision_override')
    op.drop_table('forensic_profile')
    op.drop_table('esg_metrics')
    # ### end Alembic commands ###
