"""Add USAS Phase 2 3 4 models

Revision ID: 73aee8dd1554
Revises: ab02c8edb21f
Create Date: 2026-02-24 14:34:46.222727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '73aee8dd1554'
down_revision: Union[str, None] = 'ab02c8edb21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_governance_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('decision_id', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('decision_rationale', sa.Text(), nullable=False),
    sa.Column('human_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('continuous_audit_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('data_source_type', sa.String(length=50), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('action_on_breach', sa.Enum('ALERT_ONLY', 'INCREASE_SAMPLE', 'TRIGGER_CRISIS', 'BLOCK_TRANSACTION', name='continuous_audit_action'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crisis_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.Enum('REGULATORY_NOTICE', 'FRAUD_DETECTED', 'LITIGATION_HOLD', 'SYSTEM_COMPROMISE', 'WHISTLEBLOWER', name='crisis_trigger_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'ARCHIVED', name='crisis_status'), nullable=False),
    sa.Column('freeze_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('escalated_by', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('esg_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('metric_category', sa.Enum('ENVIRONMENTAL', 'SOCIAL', 'GOVERNANCE', name='esg_category'), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('validation_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forensic_investigation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('target_entity', sa.String(length=255), nullable=False),
    sa.Column('investigation_type', sa.Enum('RELATED_PARTY', 'ASSET_MISAPPROPRIATION', 'FINANCIAL_STATEMENT_FRAUD', 'CORRUPTION', name='investigation_type'), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sovereign_archive',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('archive_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SEALED', 'PENDING', 'COMPROMISED', name='archive_status'), nullable=False),
    sa.Column('archive_location', sa.String(length=500), nullable=False),
    sa.Column('retention_period_years', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_table('sovereign_archive')
    op.drop_table('forensic_investigation')
    op.drop_table('esg_metric')
    op.drop_table('crisis_event')
    op.drop_table('continuous_audit_rule')
    op.drop_table('ai_governance_log')
    # ### end Alembic commands ###
