# pyre-ignore-all-errors
"""Add USAS Phase 1 models

Revision ID: ab02c8edb21f
Revises: b66fe5cf332c
Create Date: 2026-02-24 14:19:57.433652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab02c8edb21f'
down_revision: Union[str, None] = 'b66fe5cf332c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_playbook',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_type', postgresql.ENUM('STATUTORY_AUDIT', 'INTERNAL_AUDIT', 'FORENSIC_AUDIT', 'IT_AUDIT', 'AGREED_UPON_PROCEDURES', name='engagement_type', create_type=False), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('playbook_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_template_id', sa.String(length=128), nullable=False),
    sa.Column('required_phases', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cross_border_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('target_jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('enforcement_action', sa.Enum('WARN', 'BLOCK', 'REQUIRE_APPROVAL', 'LOG_ONLY', name='policy_enforcement_action'), nullable=False),
    sa.Column('constraint_details', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_framework',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('framework_type', sa.Enum('IFRS', 'US_GAAP', 'IND_AS', 'LOCAL_GAAP', 'PCAOB', 'ISA', 'OTHER', name='framework_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_control',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_mapping', sa.JSON(), nullable=False),
    sa.Column('test_procedures', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom downgrade cleanup for auto-generated script
    op.drop_table('sector_control')
    op.drop_table('regulatory_framework')
    op.drop_table('cross_border_policy')
    op.drop_table('audit_playbook')
    # ### end Alembic commands ###
