"""Add auditor workflow models

Revision ID: b66fe5cf332c
Revises: 20260224_0006
Create Date: 2026-02-24 14:04:34.691170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b66fe5cf332c'
down_revision: Union[str, None] = '20260224_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('engagement_type', sa.Enum('STATUTORY_AUDIT', 'INTERNAL_AUDIT', 'FORENSIC_AUDIT', 'IT_AUDIT', 'AGREED_UPON_PROCEDURES', name='engagement_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='engagement_status'), nullable=False),
    sa.Column('independence_cleared', sa.Boolean(), nullable=False),
    sa.Column('kyc_cleared', sa.Boolean(), nullable=False),
    sa.Column('conflict_check_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engagement_tenant_jurisdiction_status', 'engagement', ['tenant_id', 'jurisdiction', 'status'], unique=False)
    op.create_table('audit_opinion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('opinion_type', sa.Enum('UNMODIFIED', 'QUALIFIED', 'ADVERSE', 'DISCLAIMER', name='audit_opinion_type'), nullable=False),
    sa.Column('basis_for_opinion', sa.Text(), nullable=False),
    sa.Column('key_audit_matters', sa.JSON(), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('signed_by', sa.String(length=100), nullable=True),
    sa.Column('signature_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiality_assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('basis', sa.Enum('REVENUE', 'PROFIT_BEFORE_TAX', 'TOTAL_ASSETS', 'NET_ASSETS', 'GROSS_MARGIN', name='materiality_basis'), nullable=False),
    sa.Column('basis_amount', sa.Float(), nullable=False),
    sa.Column('overall_percentage', sa.Float(), nullable=False),
    sa.Column('overall_materiality', sa.Float(), nullable=False),
    sa.Column('performance_percentage', sa.Float(), nullable=False),
    sa.Column('performance_materiality', sa.Float(), nullable=False),
    sa.Column('trivial_threshold_percentage', sa.Float(), nullable=False),
    sa.Column('trivial_threshold', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('materiality_assessment')
    op.drop_table('audit_opinion')
    op.drop_index('ix_engagement_tenant_jurisdiction_status', table_name='engagement')
    op.drop_table('engagement')
    # ### end Alembic commands ###
